import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { createClient } from "@/lib/supabase/server";
import { PresentationViewer } from "@/components/presentation-viewer";

interface PageProps {
  params: Promise<{ id: string }>;
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { id } = await params;
  const supabase = await createClient();

  const { data } = await supabase
    .from("presentations")
    .select("title, description, thumbnail_url")
    .eq("id", id)
    .single();

  if (!data) {
    return { title: "Presentation Not Found" };
  }

  return {
    title: `${data.title} - Sdecky`,
    description: data.description || "A professional presentation generated by Sdecky.",
    openGraph: {
      title: data.title,
      description: data.description || "A professional presentation generated by Sdecky.",
      ...(data.thumbnail_url ? { images: [data.thumbnail_url] } : {}),
    },
  };
}

export default async function PresentationPage({ params }: PageProps) {
  const { id } = await params;
  const supabase = await createClient();

  const { data, error } = await supabase
    .from("presentations")
    .select("id, title, description, pdf_url, is_free")
    .eq("id", id)
    .single();

  if (error || !data) {
    notFound();
  }

  return (
    <PresentationViewer
      id={data.id}
      title={data.title}
      description={data.description ?? undefined}
      pdfUrl={data.pdf_url}
      isFree={data.is_free ?? false}
    />
  );
}
