"use client";

import { useEffect, useState } from "react";
import { FileText, ChevronLeft, ChevronRight } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { PresentationPreviewDialog } from "./presentation-preview-dialog";

interface Presentation {
  id: string;
  title: string;
  description: string;
  pdf_url: string;
  thumbnail_url?: string;
  is_free?: boolean;
}

const INITIAL_ITEMS: Presentation[] = [];

export function Gallery() {
  const [items, setItems] = useState<Presentation[]>(INITIAL_ITEMS);
  const [loading, setLoading] = useState(true);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [previewOpen, setPreviewOpen] = useState(false);
  const [selectedPresentation, setSelectedPresentation] =
    useState<Presentation | null>(null);

  useEffect(() => {
    async function fetchPresentations() {
      try {
        const supabase = createClient();
        const { data, error } = await supabase
          .from("presentations")
          .select("*")
          .order("created_at", { ascending: false });

        if (error) {
          console.error("Error fetching gallery items:", error);
          return;
        }

        if (data && data.length > 0) {
          setItems(data.slice(0, 6)); // Limit to 6 items
        } else {
          setItems([]);
        }
      } finally {
        setLoading(false);
      }
    }

    fetchPresentations();
  }, []);

  const handlePrevious = () => {
    setCurrentIndex((prev) => (prev === 0 ? items.length - 1 : prev - 1));
  };

  const handleNext = () => {
    setCurrentIndex((prev) => (prev === items.length - 1 ? 0 : prev + 1));
  };

  const currentItem = items[currentIndex];

  if (loading || items.length === 0) {
    return (
      <section id="gallery" className="w-full py-16 md:py-24 bg-[#051C2C]">
        <div className="container px-4 md:px-8 lg:px-12 mx-auto max-w-7xl">
          <div className="flex flex-col items-center justify-center space-y-4 md:space-y-6 text-center">
            <h2 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-serif font-normal text-white leading-tight px-4">
              Professional presentations,
              <br />
              powered by AI
            </h2>
            <p className="text-base sm:text-lg md:text-xl text-white/80 max-w-3xl font-light leading-relaxed px-4">
              {loading ? "Loading presentations..." : "No presentations available yet."}
            </p>
          </div>
        </div>
      </section>
    );
  }

  return (
    <section id="gallery" className="w-full py-16 md:py-24 bg-[#051C2C]">
      <div className="container px-4 md:px-8 lg:px-12 mx-auto max-w-7xl">
        {/* Section Header */}
        <div className="flex flex-col items-center justify-center space-y-4 md:space-y-6 text-center mb-12 md:mb-16">
          <h2 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-serif font-normal text-white leading-tight px-4">
            Professional presentations,
            <br />
            powered by AI
          </h2>
          <p className="text-base sm:text-lg md:text-xl text-white/80 max-w-3xl font-light leading-relaxed px-4">
            Explore the gallery of presentations generated by Sdecky.
          </p>
        </div>

        {/* Carousel Container */}
        <div className="relative max-w-5xl mx-auto">
          {/* Main Presentation Card */}
          <article
            onClick={() => {
              setSelectedPresentation(currentItem);
              setPreviewOpen(true);
            }}
            className="bg-white rounded-sm overflow-hidden hover:shadow-2xl transition-shadow duration-500 cursor-pointer"
          >
            {/* Thumbnail */}
            <div className="aspect-[16/9] relative bg-[#F0F0F0] overflow-hidden">
              {currentItem.thumbnail_url ? (
                <img
                  src={currentItem.thumbnail_url}
                  alt={currentItem.title}
                  className="w-full h-full object-contain"
                />
              ) : (
                <div className="flex items-center justify-center h-full">
                  <FileText className="w-16 h-16 md:w-20 md:h-20 text-[#5A6780]" />
                </div>
              )}
            </div>

            {/* Content */}
            <div className="p-6 md:p-8 space-y-3 md:space-y-4">
              <h3 className="font-serif text-xl md:text-2xl font-normal text-[#051C2C] line-clamp-2">
                {currentItem.title}
              </h3>
              <p className="text-sm md:text-base text-[#5A6780] line-clamp-3 leading-relaxed">
                {currentItem.description}
              </p>

              {/* Action Link */}
              <div className="flex gap-4 md:gap-6 pt-2 md:pt-4">
                <span className="text-[#2251FF] hover:text-[#051C2C] transition-colors text-sm font-medium py-2 flex items-center gap-1">
                  View presentation
                  <span className="inline-block hover:translate-x-1 transition-transform duration-300">→</span>
                </span>
              </div>
            </div>
          </article>

          {/* Navigation Arrows */}
          {items.length > 1 && (
            <>
              <button
                onClick={handlePrevious}
                className="absolute left-0 top-1/2 -translate-y-1/2 -translate-x-4 md:-translate-x-12 w-12 h-12 md:w-14 md:h-14 rounded-full bg-white hover:bg-[#F0F0F0] transition-colors flex items-center justify-center shadow-lg"
                aria-label="Previous presentation"
              >
                <ChevronLeft className="w-6 h-6 md:w-7 md:h-7 text-[#051C2C]" />
              </button>
              <button
                onClick={handleNext}
                className="absolute right-0 top-1/2 -translate-y-1/2 translate-x-4 md:translate-x-12 w-12 h-12 md:w-14 md:h-14 rounded-full bg-white hover:bg-[#F0F0F0] transition-colors flex items-center justify-center shadow-lg"
                aria-label="Next presentation"
              >
                <ChevronRight className="w-6 h-6 md:w-7 md:h-7 text-[#051C2C]" />
              </button>
            </>
          )}
        </div>

        {/* Indicators */}
        {items.length > 1 && (
          <div className="flex justify-center gap-2 mt-8">
            {items.map((_, index) => (
              <button
                key={index}
                onClick={() => setCurrentIndex(index)}
                className={`transition-all duration-300 rounded-full ${
                  index === currentIndex
                    ? "w-8 h-2 bg-white"
                    : "w-2 h-2 bg-white/40 hover:bg-white/60"
                }`}
                aria-label={`Go to presentation ${index + 1}`}
              />
            ))}
          </div>
        )}

        {/* View More Button */}
        <div className="flex justify-center mt-12 md:mt-16">
          <a
            href="/gallery"
            className="px-8 md:px-10 py-3 md:py-4 border-2 border-white text-white text-base md:text-lg hover:bg-white hover:text-[#051C2C] transition-all duration-300"
          >
            View More Presentations →
          </a>
        </div>
      </div>

      {/* Presentation Preview Dialog */}
      {selectedPresentation && (
        <PresentationPreviewDialog
          isOpen={previewOpen}
          onClose={() => {
            setPreviewOpen(false);
            setSelectedPresentation(null);
          }}
          title={selectedPresentation.title}
          pdfUrl={selectedPresentation.pdf_url}
          isFree={selectedPresentation.is_free ?? false}
        />
      )}
    </section>
  );
}
