"use client";

import { useEffect, useState } from "react";
import { FileText } from "lucide-react";
import { motion } from "framer-motion";
import { createClient } from "@/lib/supabase/client";
import { PresentationPreviewDialog } from "./presentation-preview-dialog";

interface Presentation {
  id: string;
  title: string;
  description: string;
  pdf_url: string;
  thumbnail_url?: string;
  is_free?: boolean;
  is_featured?: boolean;
}

const INITIAL_ITEMS: Presentation[] = [];

export function Gallery() {
  const [items, setItems] = useState<Presentation[]>(INITIAL_ITEMS);
  const [loading, setLoading] = useState(true);
  const [previewOpen, setPreviewOpen] = useState(false);
  const [selectedPresentation, setSelectedPresentation] =
    useState<Presentation | null>(null);

  useEffect(() => {
    async function fetchPresentations() {
      try {
        const supabase = createClient();
        const { data, error } = await supabase
          .from("presentations")
          .select("*")
          .eq("is_featured", true)
          .order("created_at", { ascending: false });

        if (error) {
          console.error("Error fetching gallery items:", error);
          return;
        }

        if (data && data.length > 0) {
          setItems(data);
        } else {
          setItems([]);
        }
      } finally {
        setLoading(false);
      }
    }

    fetchPresentations();
  }, []);

  return (
    <section id="gallery" className="w-full py-16 md:py-24 bg-[#051C2C]">
      <div className="container px-4 md:px-8 lg:px-12 mx-auto max-w-7xl">
        {/* Section Header */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.8, ease: "easeOut" }}
          className="flex flex-col items-center justify-center space-y-4 md:space-y-6 text-center mb-12 md:mb-16"
        >
          <h2 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-serif font-normal text-white leading-tight px-4">
            Professional Presentations
            <br />
          </h2>
          <p className="text-base sm:text-lg md:text-xl text-white/80 max-w-3xl font-light leading-relaxed px-4">
            Explore the gallery of presentations generated by Sdecky.
          </p>
        </motion.div>

        {/* Cards Grid - 1 Column Mobile, 2 Columns Desktop */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 md:gap-12">
          {items.slice(0, 6).map((item, index) => (
            <motion.article
              key={item.id}
              initial={{ opacity: 0, y: 40 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-50px" }}
              transition={{
                duration: 0.6,
                delay: index * 0.15,
                ease: "easeOut"
              }}
              onClick={() => {
                setSelectedPresentation(item);
                setPreviewOpen(true);
              }}
              className="group bg-white rounded-sm overflow-hidden hover:shadow-2xl transition-shadow duration-500 cursor-pointer flex flex-col"
            >
              {/* Thumbnail */}
              <div className="aspect-[16/9] relative bg-[#F0F0F0] overflow-hidden">
                {item.thumbnail_url ? (
                  <img
                    src={item.thumbnail_url}
                    alt={item.title}
                    className="w-full h-full object-contain group-hover:scale-105 transition-transform duration-700"
                  />
                ) : (
                  <div className="flex items-center justify-center h-full">
                    <FileText className="w-16 h-16 md:w-20 md:h-20 text-[#5A6780]" />
                  </div>
                )}
              </div>

              {/* Content */}
              <div className="p-6 md:p-8 space-y-3 md:space-y-4 flex flex-col flex-1">
                <h3 className="font-serif text-xl md:text-2xl font-normal text-[#051C2C] line-clamp-2">
                  {item.title}
                </h3>
                <p className="text-sm md:text-base text-[#5A6780] line-clamp-3 leading-relaxed flex-1">
                  {item.description}
                </p>

                {/* Action Links - Touch Optimized */}
                <div className="flex gap-4 md:gap-6 pt-2 md:pt-4 mt-auto">
                  <span className="text-[#2251FF] group-hover:text-[#051C2C] transition-colors text-sm font-medium py-2 flex items-center gap-1">
                    View presentation
                    <span className="inline-block group-hover:translate-x-1 transition-transform duration-300">→</span>
                  </span>
                </div>
              </div>
            </motion.article>
          ))}
        </div>

        {/* View More Button */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, delay: 0.3, ease: "easeOut" }}
          className="flex justify-center mt-12 md:mt-16"
        >
          <a
            href="/gallery"
            className="px-8 md:px-10 py-3 md:py-4 border-2 border-white text-white text-base md:text-lg hover:bg-white hover:text-[#051C2C] transition-all duration-300"
          >
            View More Presentations →
          </a>
        </motion.div>
      </div>

      {/* Presentation Preview Dialog */}
      {selectedPresentation && (
        <PresentationPreviewDialog
          isOpen={previewOpen}
          onClose={() => {
            setPreviewOpen(false);
            setSelectedPresentation(null);
          }}
          title={selectedPresentation.title}
          pdfUrl={selectedPresentation.pdf_url}
          isFree={selectedPresentation.is_free ?? false}
        />
      )}
    </section>
  );
}
