"use client";

import { useEffect, useState } from "react";
import { FileText } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

interface Presentation {
  id: string;
  title: string;
  description: string;
  pdf_url: string;
  thumbnail_url?: string;
}

const INITIAL_ITEMS: Presentation[] = [
  {
    id: "static-1",
    title: "Manus CTO Presentation",
    description: "Peak sharing about AI product taste",
    pdf_url: "/showcase/Manus首席科学家Peak分享关于AI产品的品味与定力-sdecky.pdf",
  },
  {
    id: "static-2",
    title: "TSMC Sdecky",
    description: "TSMC presentation generated by Sdecky",
    pdf_url: "/showcase/TSMC-Sdecky.pdf",
  },
];

export function Gallery() {
  const [items, setItems] = useState<Presentation[]>(INITIAL_ITEMS);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchPresentations() {
      try {
        const supabase = createClient();
        const { data, error } = await supabase
          .from("presentations")
          .select("*")
          .order("created_at", { ascending: false });

        if (error) {
          console.error("Error fetching gallery items:", error);
          return;
        }

        if (data && data.length > 0) {
          setItems([...data, ...INITIAL_ITEMS]);
        }
      } finally {
        setLoading(false);
      }
    }

    fetchPresentations();
  }, []);

  return (
    <section id="gallery" className="w-full py-16 md:py-24 bg-[#051C2C]">
      <div className="container px-4 md:px-8 lg:px-12 mx-auto max-w-7xl">
        {/* Section Header */}
        <div className="flex flex-col items-center justify-center space-y-4 md:space-y-6 text-center mb-12 md:mb-16">
          <h2 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-serif font-normal text-white leading-tight px-4">
            Professional presentations,
            <br />
            powered by AI
          </h2>
          <p className="text-base sm:text-lg md:text-xl text-white/80 max-w-3xl font-light leading-relaxed px-4">
            Explore the gallery of presentations generated by Sdecky.
          </p>
        </div>

        {/* Cards Grid - 1 Column Mobile, 2 Columns Desktop */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 md:gap-12">
          {items.slice(0, 4).map((item) => (
            <article
              key={item.id}
              className="group bg-white rounded-sm overflow-hidden hover:shadow-2xl transition-shadow duration-500"
            >
              {/* Thumbnail */}
              <div className="aspect-[16/10] relative bg-[#F0F0F0] overflow-hidden">
                {item.thumbnail_url ? (
                  <img
                    src={item.thumbnail_url}
                    alt={item.title}
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"
                  />
                ) : (
                  <div className="flex items-center justify-center h-full">
                    <FileText className="w-16 h-16 md:w-20 md:h-20 text-[#5A6780]" />
                  </div>
                )}
              </div>

              {/* Content */}
              <div className="p-6 md:p-8 space-y-3 md:space-y-4">
                <h3 className="font-serif text-xl md:text-2xl font-normal text-[#051C2C] line-clamp-2">
                  {item.title}
                </h3>
                <p className="text-sm md:text-base text-[#5A6780] line-clamp-3 leading-relaxed">
                  {item.description}
                </p>

                {/* Action Links - Touch Optimized */}
                <div className="flex gap-4 md:gap-6 pt-2 md:pt-4">
                  <a
                    href={item.pdf_url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-[#2251FF] hover:text-[#051C2C] active:text-[#051C2C] transition-colors text-sm font-medium py-2"
                  >
                    View presentation →
                  </a>
                  <a
                    href={item.pdf_url}
                    download
                    className="text-[#5A6780] hover:text-[#051C2C] active:text-[#051C2C] transition-colors text-sm py-2"
                  >
                    Download
                  </a>
                </div>
              </div>
            </article>
          ))}
        </div>

        {/* View More Button */}
        <div className="flex justify-center mt-12 md:mt-16">
          <a
            href="/gallery"
            className="px-8 md:px-10 py-3 md:py-4 border-2 border-white text-white text-base md:text-lg hover:bg-white hover:text-[#051C2C] transition-all duration-300"
          >
            View More Presentations →
          </a>
        </div>
      </div>
    </section>
  );
}
