import Image from "next/image";

export function Hero() {
  return (
    <section className="relative w-full h-screen flex items-center justify-center text-center overflow-hidden">
      {/* Background Image with Dark Overlay */}
      <div className="absolute inset-0 z-0">
        <Image
          src="/hero-background.jpg"
          alt="Background"
          fill
          className="object-cover brightness-[0.35]"
          priority
        />
      </div>

      {/* Content */}
      <div className="relative z-10 max-w-5xl px-4 md:px-6 space-y-6 md:space-y-8">
        {/* Main Headline - Serif Font, Responsive Size */}
        <h1 className="font-serif text-4xl sm:text-5xl md:text-6xl lg:text-7xl xl:text-8xl font-normal leading-tight text-white">
          Every great idea deserves a{" "}
          <span className="text-[#2251FF]">professional</span>{" "}
          presentation.
        </h1>

        {/* Subheadline */}
        <p className="text-base sm:text-lg md:text-xl lg:text-2xl text-white/90 max-w-3xl mx-auto font-light leading-relaxed px-4">
          Generated by AI, refined by taste. Experience the perfect blend of
          storytelling logic and aesthetic excellence.
        </p>

        {/* CTA Buttons - McKinsey Style, Mobile Optimized */}
        <div className="flex flex-col sm:flex-row gap-4 sm:gap-6 justify-center pt-4 md:pt-8 px-4">
          <a
            href="/waitlist"
            className="px-6 sm:px-8 py-3 sm:py-4 border-2 border-white text-white text-base sm:text-lg hover:bg-white hover:text-[#051C2C] transition-all duration-300 text-center"
          >
            Join Waitlist →
          </a>
          <a
            href="/gallery"
            className="px-6 sm:px-8 py-3 sm:py-4 text-white text-base sm:text-lg hover:text-white/70 transition-colors text-center"
          >
            View Gallery →
          </a>
        </div>
      </div>
    </section>
  );
}
