"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { FileText } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { MobileNav } from "@/components/mobile-nav";
import { PresentationPreviewDialog } from "@/components/presentation-preview-dialog";

interface Presentation {
  id: string;
  title: string;
  description: string;
  pdf_url: string;
  thumbnail_url?: string;
  language?: string;
  is_free?: boolean;
}

const INITIAL_ITEMS: Presentation[] = [
  {
    id: "static-1",
    title: "Manus CTO Presentation",
    description: "Peak sharing about AI product taste",
    pdf_url: "/showcase/Manus首席科学家Peak分享关于AI产品的品味与定力-sdecky.pdf",
    language: "zh",
    is_free: true, // Static examples are free
  },
  {
    id: "static-2",
    title: "TSMC Sdecky",
    description: "TSMC presentation generated by Sdecky",
    pdf_url: "/showcase/TSMC-Sdecky.pdf",
    language: "en",
    is_free: true, // Static examples are free
  },
];

const LANGUAGES = [
  { code: "all", name: "All Languages" },
  { code: "en", name: "English" },
  { code: "zh", name: "中文" },
  { code: "ja", name: "日本語" },
];

export default function GalleryPage() {
  const [items, setItems] = useState<Presentation[]>(INITIAL_ITEMS);
  const [loading, setLoading] = useState(true);
  const [selectedLanguage, setSelectedLanguage] = useState("all");
  const [previewOpen, setPreviewOpen] = useState(false);
  const [selectedPresentation, setSelectedPresentation] =
    useState<Presentation | null>(null);

  useEffect(() => {
    async function fetchPresentations() {
      try {
        const supabase = createClient();
        const { data, error } = await supabase
          .from("presentations")
          .select("*")
          .order("created_at", { ascending: false });

        if (error) {
          console.error("Error fetching gallery items:", error);
          return;
        }

        if (data && data.length > 0) {
          setItems([...data, ...INITIAL_ITEMS]);
        }
      } finally {
        setLoading(false);
      }
    }

    fetchPresentations();
  }, []);

  // Filter presentations by language
  const filteredItems =
    selectedLanguage === "all"
      ? items
      : items.filter((item) => item.language === selectedLanguage);

  return (
    <div className="min-h-screen bg-white">
      {/* Navigation Bar */}
      <nav className="fixed top-0 w-full bg-white border-b border-[#E0E0E0] z-50">
        <div className="container mx-auto px-4 md:px-8">
          <div className="flex items-center justify-between h-20 md:h-24">
            {/* Logo Section */}
            <Link href="/" className="flex flex-col">
              <span className="text-2xl md:text-4xl font-serif font-bold text-[#051C2C]">
                Sdecky
              </span>
            </Link>

            {/* Desktop Navigation Links */}
            <div className="hidden md:flex flex-col items-end">
              {/* Navigation Items */}
              <div className="flex gap-8 items-center">
                <Link
                  href="/gallery"
                  className="relative text-lg text-[#051C2C] hover:text-[#2251FF] transition-colors pb-1 group"
                >
                  Gallery
                  <span className="absolute bottom-0 left-0 w-0 h-0.5 bg-[#2251FF] group-hover:w-full transition-all duration-300"></span>
                </Link>
                <Link
                  href="/waitlist"
                  className="relative text-lg text-[#051C2C] hover:text-[#2251FF] transition-colors pb-1 group"
                >
                  Join Waitlist
                  <span className="absolute bottom-0 left-0 w-0 h-0.5 bg-[#2251FF] group-hover:w-full transition-all duration-300"></span>
                </Link>
              </div>
            </div>

            {/* Mobile Navigation */}
            <MobileNav />
          </div>
        </div>
      </nav>

      {/* Page Content */}
      <div className="pt-20 md:pt-24">
        {/* Hero Section */}
        <section className="w-full py-16 md:py-24 bg-[#051C2C]">
          <div className="container px-4 md:px-8 lg:px-12 mx-auto max-w-7xl">
            <div className="flex flex-col items-center justify-center space-y-4 md:space-y-6 text-center">
              <h1 className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-serif font-normal text-white leading-tight px-4">
                Professional Presentations Gallery
              </h1>
              <p className="text-base sm:text-lg md:text-xl text-white/80 max-w-3xl font-light leading-relaxed px-4">
                Explore our collection of AI-generated presentations across multiple languages and industries.
              </p>
            </div>
          </div>
        </section>

        {/* Language Filter */}
        <section className="w-full py-8 bg-white border-b border-[#F0F0F0]">
          <div className="container px-4 md:px-8 lg:px-12 mx-auto max-w-7xl">
            <div className="flex flex-wrap gap-3 justify-center">
              {LANGUAGES.map((lang) => (
                <button
                  key={lang.code}
                  onClick={() => setSelectedLanguage(lang.code)}
                  className={`px-4 md:px-6 py-2 md:py-2.5 text-sm md:text-base rounded-sm transition-all ${
                    selectedLanguage === lang.code
                      ? "bg-[#051C2C] text-white"
                      : "bg-white border border-[#E0E0E0] text-[#051C2C] hover:border-[#051C2C]"
                  }`}
                >
                  {lang.name}
                </button>
              ))}
            </div>
          </div>
        </section>

        {/* Gallery Grid */}
        <section className="w-full py-16 bg-white">
          <div className="container px-4 md:px-8 lg:px-12 mx-auto max-w-7xl">
            {loading ? (
              <div className="text-center py-12">
                <p className="text-[#5A6780]">Loading presentations...</p>
              </div>
            ) : filteredItems.length === 0 ? (
              <div className="text-center py-12">
                <p className="text-[#5A6780]">No presentations found for this language.</p>
              </div>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                {filteredItems.map((item) => (
                  <article
                    key={item.id}
                    className="group bg-white border border-[#F0F0F0] rounded-sm overflow-hidden hover:shadow-2xl transition-shadow duration-500"
                  >
                    {/* Thumbnail */}
                    <div className="aspect-[16/10] relative bg-[#F0F0F0] overflow-hidden">
                      {item.thumbnail_url ? (
                        <img
                          src={item.thumbnail_url}
                          alt={item.title}
                          className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"
                        />
                      ) : (
                        <div className="flex items-center justify-center h-full">
                          <FileText className="w-16 h-16 md:w-20 md:h-20 text-[#5A6780]" />
                        </div>
                      )}
                    </div>

                    {/* Content */}
                    <div className="p-6 space-y-3">
                      <h3 className="font-serif text-xl font-normal text-[#051C2C] line-clamp-2">
                        {item.title}
                      </h3>
                      <p className="text-sm text-[#5A6780] line-clamp-3 leading-relaxed">
                        {item.description}
                      </p>

                      {/* Action Links */}
                      <div className="flex gap-4 pt-2">
                        <button
                          onClick={() => {
                            setSelectedPresentation(item);
                            setPreviewOpen(true);
                          }}
                          className="text-[#2251FF] hover:text-[#051C2C] transition-colors text-sm font-medium"
                        >
                          View →
                        </button>
                      </div>
                    </div>
                  </article>
                ))}
              </div>
            )}
          </div>
        </section>
      </div>

      {/* Presentation Preview Dialog */}
      {selectedPresentation && (
        <PresentationPreviewDialog
          isOpen={previewOpen}
          onClose={() => {
            setPreviewOpen(false);
            setSelectedPresentation(null);
          }}
          title={selectedPresentation.title}
          pdfUrl={selectedPresentation.pdf_url}
          isFree={selectedPresentation.is_free ?? false}
        />
      )}
    </div>
  );
}
